recipe: default.v1
language: es
assistant_id: la-meva-salut

pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: rasa_command_generation_model
  flow_retrieval:
    active: false

policies:
- name: FlowPolicy
  ask_before_continuing_flow: false
